// This script seeds the Firestore database with the itinerary data
// Run: npx ts-node scripts/seed-itinerary.ts

import { addItineraryItems } from "@/lib/firestore";
import { ItineraryItem } from "@/types/index";

const TRIP_ID = "sg-my-2026";

// Itinerary data extracted from the Excel spreadsheet
const itineraryData: Omit<ItineraryItem, "id" | "tripId">[] = [
  // Day 1: Wed 29/4 - Singapore Arrival
  {
    day: 1,
    date: "2026-04-29",
    time: "12:50",
    location: "Hanoi",
    activity: "✈️ Depart for Singapore (Scoot)",
    estimatedPrice: { amount: 0, currency: "SGD" },
    notes: "Flight SQ7 to Singapore Changi",
    order: 1,
    visited: false,
  },
  {
    day: 1,
    date: "2026-04-29",
    time: "17:10",
    location: "Singapore Changi Airport - T1",
    activity: "🛄 Collect baggage",
    estimatedPrice: { amount: 0, currency: "SGD" },
    notes: "Drop off at desk, get SIM card at Travelex/Cheers",
    order: 2,
    visited: false,
  },
  {
    day: 1,
    date: "2026-04-29",
    time: "17:30",
    location: "Jewel Changi Airport",
    activity: "💎 Explore Jewel (Rain Vortex, photos)",
    estimatedPrice: { amount: 20, currency: "SGD" },
    notes: "Food Court B2, Solce Studio (free photobooth), may visit Canopy Park",
    order: 3,
    visited: false,
  },
  {
    day: 1,
    date: "2026-04-29",
    time: "19:30",
    location: "Changi → Aljunied",
    activity: "🚇 MRT to Hotel",
    estimatedPrice: { amount: 3.78, currency: "SGD" },
    notes: "Changi T2 → Tanah Merah (MUST transfer) → Aljunied → Walk 8 min",
    order: 4,
    visited: false,
  },
  {
    day: 1,
    date: "2026-04-29",
    time: "20:00",
    location: "Old Chang Kee, Geylang",
    activity: "🍢 Dinner at Old Chang Kee",
    estimatedPrice: { amount: 10, currency: "SGD" },
    notes: "Fried chicken + cuttlefish poutine - appetizer",
    order: 5,
    visited: false,
  },
  {
    day: 1,
    date: "2026-04-29",
    time: "20:30",
    location: "ibis budget Singapore Pearl",
    activity: "🏨 Check-in",
    estimatedPrice: { amount: 0, currency: "SGD" },
    notes: "21 Lorong 14 Geylang",
    order: 6,
    visited: false,
  },
  {
    day: 1,
    date: "2026-04-29",
    time: "21:00",
    location: "Geylang Lorong 9",
    activity: "🐸 Dinner: Fresh Frog Porridge",
    estimatedPrice: { amount: 35, currency: "SGD" },
    notes: "Frog congee + oyster omelette - MUST TRY",
    order: 7,
    visited: false,
  },

  // Day 2: Thu 30/4
  {
    day: 2,
    date: "2026-04-30",
    time: "07:30",
    location: "Dhoby Ghaut",
    activity: "☕ Breakfast: Ya Kun Kaya Toast",
    estimatedPrice: { amount: 12, currency: "SGD" },
    notes: "Kaya toast + soft boiled eggs + kopi",
    order: 1,
    visited: false,
  },
  {
    day: 2,
    date: "2026-04-30",
    time: "08:00",
    location: "Fort Canning Park",
    activity: "🏛️ Fort Canning + Old Hill Street Police Station",
    estimatedPrice: { amount: 0, currency: "SGD" },
    notes: "Walk from Dhoby Ghaut (~5 min), rainbow building photo spot",
    order: 2,
    visited: false,
  },
  {
    day: 2,
    date: "2026-04-30",
    time: "10:00",
    location: "National Gallery Singapore",
    activity: "🎨 National Gallery Singapore",
    estimatedPrice: { amount: 0, currency: "SGD" },
    notes: "ASEAN citizens free | Non-ASEAN: $20 ~1.5h",
    order: 3,
    visited: false,
  },
  {
    day: 2,
    date: "2026-04-30",
    time: "11:30",
    location: "Chinatown",
    activity: "🏮 Lunch: Tian Tian + Mei Heong Yuen",
    estimatedPrice: { amount: 25, currency: "SGD" },
    notes: "Hainanese chicken rice + dessert",
    order: 4,
    visited: false,
  },
  {
    day: 2,
    date: "2026-04-30",
    time: "13:15",
    location: "Kampong Glam cluster",
    activity: "🕌 Kampong Glam (Sultan Mosque + Haji Lane + Bugis)",
    estimatedPrice: { amount: 15, currency: "SGD" },
    notes: "Street art, shopping, mosque visit",
    order: 5,
    visited: false,
  },
  {
    day: 2,
    date: "2026-04-30",
    time: "15:00",
    location: "Sim Lim Square",
    activity: "🍜 3 Meals a Day (Sichuan noodles)",
    estimatedPrice: { amount: 20, currency: "SGD" },
    notes: "Viral spicy Sichuan ramen",
    order: 6,
    visited: false,
  },
  {
    day: 2,
    date: "2026-04-30",
    time: "16:00",
    location: "ibis budget Singapore Pearl",
    activity: "🛌 Rest at hotel",
    estimatedPrice: { amount: 0, currency: "SGD" },
    notes: "Avoid afternoon heat, recharge batteries",
    order: 7,
    visited: false,
  },
  {
    day: 2,
    date: "2026-04-30",
    time: "17:30",
    location: "Merlion Park",
    activity: "🦁 Merlion Park + Marina Bay Sunset",
    estimatedPrice: { amount: 0, currency: "SGD" },
    notes: "Best photos 18:30-19:30, sunset ~19:04",
    order: 8,
    visited: false,
  },
  {
    day: 2,
    date: "2026-04-30",
    time: "19:30",
    location: "Queenstown",
    activity: "🦀 Chili Crab at Keng Eng Kee",
    estimatedPrice: { amount: 70, currency: "SGD" },
    notes: "Must-try! Book 7pm slot",
    order: 9,
    visited: false,
  },
  {
    day: 2,
    date: "2026-04-30",
    time: "21:30",
    location: "ibis budget Singapore Pearl",
    activity: "🚇 Return to hotel",
    estimatedPrice: { amount: 3.38, currency: "SGD" },
    notes: "",
    order: 10,
    visited: false,
  },

  // Day 3: Fri 1/5 - Singapore to Malaysia
  {
    day: 3,
    date: "2026-05-01",
    time: "07:30",
    location: "Jalan Besar",
    activity: "🥟 Breakfast: Swee Choon Dim Sum",
    estimatedPrice: { amount: 25, currency: "SGD" },
    notes: "Famous dim sum, opens 7:00 AM",
    order: 1,
    visited: false,
  },
  {
    day: 3,
    date: "2026-05-01",
    time: "08:30",
    location: "Koon Seng Road",
    activity: "🏠 Peranakan Houses",
    estimatedPrice: { amount: 0, currency: "SGD" },
    notes: "Colorful heritage houses, great photo spot",
    order: 2,
    visited: false,
  },
  {
    day: 3,
    date: "2026-05-01",
    time: "10:30",
    location: "ibis budget Singapore Pearl",
    activity: "🏨 Check out & collect luggage",
    estimatedPrice: { amount: 0, currency: "SGD" },
    notes: "",
    order: 3,
    visited: false,
  },
  {
    day: 3,
    date: "2026-05-01",
    time: "11:00",
    location: "Tai Seng MRT",
    activity: "🚇 Head to bus station",
    estimatedPrice: { amount: 2.18, currency: "SGD" },
    notes: "Walk 10 min → Paya Lebar MRT → Tai Seng (1 stop)",
    order: 4,
    visited: false,
  },
  {
    day: 3,
    date: "2026-05-01",
    time: "12:00",
    location: "Terminal Bersepadu Selatan, KL",
    activity: "🚌 Bus: SG → KL (Seat 2B, 2C)",
    estimatedPrice: { amount: 542, currency: "MYR" },
    notes: "5h 28m journey, rest on bus",
    order: 5,
    visited: false,
  },
  {
    day: 3,
    date: "2026-05-01",
    time: "17:30",
    location: "1000 Miles Hotel",
    activity: "🚗 Grab to hotel",
    estimatedPrice: { amount: 15, currency: "MYR" },
    notes: "Check-in at 1000 Miles Hotel",
    order: 6,
    visited: false,
  },
  {
    day: 3,
    date: "2026-05-01",
    time: "18:30",
    location: "Petaling Street",
    activity: "🍜 Dinner: Chinatown Street Food",
    estimatedPrice: { amount: 50, currency: "MYR" },
    notes: "Madras Lane or Petaling snacks, night market ~18h+",
    order: 7,
    visited: false,
  },

  // Day 4: Sat 2/5
  {
    day: 4,
    date: "2026-05-02",
    time: "09:00",
    location: "Chow Kit",
    activity: "🚗 Grab to Chow Kit",
    estimatedPrice: { amount: 8, currency: "MYR" },
    notes: "3 km, 10 min",
    order: 1,
    visited: false,
  },
  {
    day: 4,
    date: "2026-05-02",
    time: "09:30",
    location: "Chow Kit",
    activity: "📸 Chow Kit street photos",
    estimatedPrice: { amount: 0, currency: "MYR" },
    notes: "Old street, street art, wet market",
    order: 2,
    visited: false,
  },
  {
    day: 4,
    date: "2026-05-02",
    time: "10:00",
    location: "Chow Kit",
    activity: "🍳 Breakfast: Yut Kee (since 1928)",
    estimatedPrice: { amount: 50, currency: "MYR" },
    notes: "Roti babi, Hainanese chicken chop, egg kopi",
    order: 3,
    visited: false,
  },
  {
    day: 4,
    date: "2026-05-02",
    time: "11:00",
    location: "Cheevit Cheeva",
    activity: "🍧 Dessert: Cheevit Cheeva (Thai Bingsu)",
    estimatedPrice: { amount: 60, currency: "MYR" },
    notes: "Beautiful Instagram-worthy space",
    order: 4,
    visited: false,
  },
  {
    day: 4,
    date: "2026-05-02",
    time: "13:00",
    location: "Putrajaya",
    activity: "🕌 Putrajaya Mosque (Masjid Putra)",
    estimatedPrice: { amount: 30, currency: "MYR" },
    notes: "30 km, 35 min | Red mosque, panorama skyline | Borrow abaya if needed",
    order: 5,
    visited: false,
  },
  {
    day: 4,
    date: "2026-05-02",
    time: "15:30",
    location: "KLCC",
    activity: "🏙️ KLCC Park + Petronas Twin Towers",
    estimatedPrice: { amount: 30, currency: "MYR" },
    notes: "30 km, 35 min | Free photos from park",
    order: 6,
    visited: false,
  },
  {
    day: 4,
    date: "2026-05-02",
    time: "18:00",
    location: "KLCC",
    activity: "🍜 Dinner: Oriental Kopi",
    estimatedPrice: { amount: 50, currency: "MYR" },
    notes: "Queue 30-60 min, arrive early, authentic Malaysian",
    order: 7,
    visited: false,
  },
  {
    day: 4,
    date: "2026-05-02",
    time: "20:00",
    location: "KLCC",
    activity: "🧋 Teh Tarik (Bungkus Kawkaw)",
    estimatedPrice: { amount: 25, currency: "MYR" },
    notes: "Pulled tea, cute packaging - souvenir",
    order: 8,
    visited: false,
  },
  {
    day: 4,
    date: "2026-05-02",
    time: "20:30",
    location: "KLCC",
    activity: "⛲ KLCC Light Show (free)",
    estimatedPrice: { amount: 0, currency: "MYR" },
    notes: "20:00 / 21:00 / 22:00 shows",
    order: 9,
    visited: false,
  },
  {
    day: 4,
    date: "2026-05-02",
    time: "21:00",
    location: "1000 Miles Hotel",
    activity: "🚗 Grab back to hotel",
    estimatedPrice: { amount: 12, currency: "MYR" },
    notes: "5 km, 15 min",
    order: 10,
    visited: false,
  },

  // Day 5: Sun 3/5
  {
    day: 5,
    date: "2026-05-03",
    time: "07:30",
    location: "Lebuh Ampang",
    activity: "☕ Breakfast: Ho Kow Hainam Kopitiam (since 1956)",
    estimatedPrice: { amount: 35, currency: "MYR" },
    notes: "Kopi, butter toast, nasi lemak - MUST TRY",
    order: 1,
    visited: false,
  },
  {
    day: 5,
    date: "2026-05-03",
    time: "08:30",
    location: "Thean Hou Temple",
    activity: "🏯 Thean Hou Temple (6-tier Chinese temple)",
    estimatedPrice: { amount: 15, currency: "MYR" },
    notes: "15-20 min Grab, rooftop KL skyline view",
    order: 2,
    visited: false,
  },
  {
    day: 5,
    date: "2026-05-03",
    time: "10:15",
    location: "Masjid Wilayah",
    activity: "🕌 Masjid Wilayah (Blue Mosque)",
    estimatedPrice: { amount: 22, currency: "MYR" },
    notes: "Otto-Mughal architecture, 25 min Grab, non-Muslim: 10-12h / 15-16h / 17:30-18:30",
    order: 3,
    visited: false,
  },
  {
    day: 5,
    date: "2026-05-03",
    time: "11:45",
    location: "Pudu",
    activity: "🍚 Lunch: Heun Kee Claypot Rice",
    estimatedPrice: { amount: 80, currency: "MYR" },
    notes: "Famous chicken claypot rice, decades old",
    order: 4,
    visited: false,
  },
  {
    day: 5,
    date: "2026-05-03",
    time: "13:30",
    location: "1000 Miles Hotel",
    activity: "🛌 Afternoon rest",
    estimatedPrice: { amount: 10, currency: "MYR" },
    notes: "Avoid midday heat, recharge for evening food tour",
    order: 5,
    visited: false,
  },
  {
    day: 5,
    date: "2026-05-03",
    time: "16:00",
    location: "BookXcess Rex KL",
    activity: "📚 BookXcess Rex KL (Unique bookstore)",
    estimatedPrice: { amount: 8, currency: "MYR" },
    notes: "4th floor, renovated cinema, great photos, cafe inside",
    order: 6,
    visited: false,
  },
  {
    day: 5,
    date: "2026-05-03",
    time: "17:50",
    location: "Jalan Ampang",
    activity: "☕ Cafe: KLCG Confectionery & Bakery",
    estimatedPrice: { amount: 40, currency: "MYR" },
    notes: "Classic pastries + cafe, relax before night food tour",
    order: 7,
    visited: false,
  },
  {
    day: 5,
    date: "2026-05-03",
    time: "19:00",
    location: "Jalan Alor",
    activity: "🍢 Jalan Alor Food Street (Night Market)",
    estimatedPrice: { amount: 100, currency: "MYR" },
    notes: "Wong Ah Wah BBQ wings MUST-TRY, lively after 19h",
    order: 8,
    visited: false,
  },
  {
    day: 5,
    date: "2026-05-03",
    time: "20:30",
    location: "Bukit Bintang",
    activity: "🍜 Win Heng Seng (Char Koay Kak)",
    estimatedPrice: { amount: 25, currency: "MYR" },
    notes: "Traditional Malaysian noodles",
    order: 9,
    visited: false,
  },
  {
    day: 5,
    date: "2026-05-03",
    time: "21:00",
    location: "1000 Miles Hotel",
    activity: "🚗 Grab back to hotel",
    estimatedPrice: { amount: 8, currency: "MYR" },
    notes: "Prepare for final day",
    order: 10,
    visited: false,
  },

  // Day 6: Mon 4/5 - Last day
  {
    day: 6,
    date: "2026-05-04",
    time: "07:30",
    location: "Chinatown",
    activity: "🥛 Breakfast: Kim Soya Bean",
    estimatedPrice: { amount: 30, currency: "MYR" },
    notes: "Soy milk + fried dough sticks",
    order: 1,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "08:15",
    location: "Chinatown",
    activity: "🛕 Sri Mahamariamman Temple",
    estimatedPrice: { amount: 0, currency: "MYR" },
    notes: "Oldest Hindu temple (1873), colorful gopuram, remove shoes",
    order: 2,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "08:45",
    location: "Chinatown",
    activity: "🎨 Kwai Chai Hong (Street Art)",
    estimatedPrice: { amount: 0, currency: "MYR" },
    notes: "6 3D murals, morning less crowded for photos",
    order: 3,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "09:30",
    location: "Petaling Street",
    activity: "🏮 Petaling Street (Old Town shopping)",
    estimatedPrice: { amount: 20, currency: "MYR" },
    notes: "Cendol, Ais Kacang, Tau Fu Fa, souvenirs",
    order: 4,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "10:15",
    location: "Central Market",
    activity: "🏛️ Central Market (Pasar Seni)",
    estimatedPrice: { amount: 0, currency: "MYR" },
    notes: "Art Deco 1888, batik, pewter, chocolate, last shopping",
    order: 5,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "11:00",
    location: "Chinatown",
    activity: "📸 Nostalgia Newsphoto (Vintage photoshoot)",
    estimatedPrice: { amount: 50, currency: "MYR" },
    notes: "Couple vintage photoshoot, includes prints, opens 11:00",
    order: 6,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "11:45",
    location: "Merdeka Square",
    activity: "🏛️ Merdeka Square + Sultan Abdul Samad Building",
    estimatedPrice: { amount: 0, currency: "MYR" },
    notes: "Independence square 1957, Moorish architecture, I❤️KL gallery",
    order: 7,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "12:30",
    location: "Chinatown",
    activity: "🍜 Lunch: Baba Can Book (Nyonya)",
    estimatedPrice: { amount: 60, currency: "MYR" },
    notes: "Authentic Peranakan/Nyonya cuisine",
    order: 8,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "13:30",
    location: "TRX Mall",
    activity: "🚗 Grab to TRX Mall",
    estimatedPrice: { amount: 12, currency: "MYR" },
    notes: "Newest, most premium mall in KL",
    order: 9,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "13:45",
    location: "TRX Mall",
    activity: "🍦 Tofu G Gelato (Dessert)",
    estimatedPrice: { amount: 30, currency: "MYR" },
    notes: "Tofu gelato signature flavor, final treat",
    order: 10,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "14:30",
    location: "1000 Miles Hotel",
    activity: "🚗 Grab to hotel",
    estimatedPrice: { amount: 10, currency: "MYR" },
    notes: "Check out, collect luggage",
    order: 11,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "15:00",
    location: "KLIA / KLIA2",
    activity: "🚗 Grab to airport",
    estimatedPrice: { amount: 65, currency: "MYR" },
    notes: "60 km, 55-75 min, arrive 2.5h before flight",
    order: 12,
    visited: false,
  },
  {
    day: 6,
    date: "2026-05-04",
    time: "19:00",
    location: "KLIA",
    activity: "✈️ Return flight to Hanoi",
    estimatedPrice: { amount: 0, currency: "MYR" },
    notes: "Check-in, duty-free, check terminal on ticket",
    order: 13,
    visited: false,
  },
];

async function seedItinerary() {
  try {
    console.log("Starting to seed itinerary data...");

    const itemsWithTrip = itineraryData.map((item) => ({
      ...item,
      tripId: TRIP_ID,
    })) as ItineraryItem[];

    await addItineraryItems(itemsWithTrip);

    console.log(`✅ Successfully seeded ${itemsWithTrip.length} itinerary items!`);
  } catch (error) {
    console.error("❌ Error seeding itinerary:", error);
    process.exit(1);
  }
}

seedItinerary();
